apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger-service
  template:
    metadata:
      labels:
        app: logger-service
    spec:
      containers:
        - image: logger-service:latest
          name: logger-service
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /api/v1/logger/
              port: 5001
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 600
            failureThreshold: 3
          ports:
            - containerPort: 5001
              name: http
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: logger-service
spec:
  selector:
    app: logger-service
  ports:
    - port: 5001
